// Maps tech name → { slug, color, logo } for shields.io badges
// https://shields.io/badges/static-badge
// logo values from https://simpleicons.org/
export const TECH_LOGOS = {
  // Frontend
  'React':          { color: '61DAFB', logo: 'react',             label: 'React' },
  'Vue':            { color: '4FC08D', logo: 'vuedotjs',          label: 'Vue.js' },
  'Vue.js':         { color: '4FC08D', logo: 'vuedotjs',          label: 'Vue.js' },
  'Angular':        { color: 'DD0031', logo: 'angular',           label: 'Angular' },
  'Svelte':         { color: 'FF3E00', logo: 'svelte',            label: 'Svelte' },
  'Next.js':        { color: '000000', logo: 'nextdotjs',         label: 'Next.js' },
  'Nuxt.js':        { color: '00DC82', logo: 'nuxtdotjs',         label: 'Nuxt.js' },
  'Remix':          { color: '000000', logo: 'remix',             label: 'Remix' },
  'Astro':          { color: 'FF5D01', logo: 'astro',             label: 'Astro' },
  'SolidJS':        { color: '2C4F7C', logo: 'solid',             label: 'SolidJS' },
  'Qwik':           { color: '18B6F6', logo: 'qwik',              label: 'Qwik' },
  'Gatsby':         { color: '663399', logo: 'gatsby',            label: 'Gatsby' },
  'Ember.js':       { color: 'E04E39', logo: 'emberdotjs',        label: 'Ember.js' },
  'Backbone.js':    { color: '0071B5', logo: 'backbonedotjs',     label: 'Backbone.js' },
  'Preact':         { color: '673AB8', logo: 'preact',            label: 'Preact' },
  'Alpine.js':      { color: '77C1D2', logo: 'alpinedotjs',       label: 'Alpine.js' },
  'Lit':            { color: '324FFF', logo: 'lit',               label: 'Lit' },
  // CSS / Styling
  'Tailwind CSS':   { color: '06B6D4', logo: 'tailwindcss',       label: 'Tailwind CSS' },
  'Tailwind':       { color: '06B6D4', logo: 'tailwindcss',       label: 'Tailwind CSS' },
  'Bootstrap':      { color: '7952B3', logo: 'bootstrap',         label: 'Bootstrap' },
  'Sass':           { color: 'CC6699', logo: 'sass',              label: 'Sass' },
  'SCSS':           { color: 'CC6699', logo: 'sass',              label: 'SCSS' },
  'Less':           { color: '1D365D', logo: 'less',              label: 'Less' },
  'Styled Components': { color: 'DB7093', logo: 'styledcomponents', label: 'Styled Components' },
  'Emotion':        { color: 'DB7093', logo: 'css3',              label: 'Emotion' },
  'Material UI':    { color: '007FFF', logo: 'mui',               label: 'Material UI' },
  'MUI':            { color: '007FFF', logo: 'mui',               label: 'MUI' },
  'Chakra UI':      { color: '319795', logo: 'chakraui',          label: 'Chakra UI' },
  'Ant Design':     { color: '1677FF', logo: 'antdesign',         label: 'Ant Design' },
  'shadcn/ui':      { color: '000000', logo: 'shadcnui',          label: 'shadcn/ui' },
  'Radix UI':       { color: '161618', logo: 'radixui',           label: 'Radix UI' },
  'Bulma':          { color: '00D1B2', logo: 'bulma',             label: 'Bulma' },
  'Mantine':        { color: '339AF0', logo: 'mantine',           label: 'Mantine' },
  'daisyUI':        { color: '5A0EF8', logo: 'daisyui',          label: 'daisyUI' },
  // Languages
  'JavaScript':     { color: 'F7DF1E', logo: 'javascript',        label: 'JavaScript' },
  'TypeScript':     { color: '3178C6', logo: 'typescript',        label: 'TypeScript' },
  'Python':         { color: '3776AB', logo: 'python',            label: 'Python' },
  'Rust':           { color: '000000', logo: 'rust',              label: 'Rust' },
  'Go':             { color: '00ADD8', logo: 'go',                label: 'Go' },
  'Golang':         { color: '00ADD8', logo: 'go',                label: 'Go' },
  'Java':           { color: 'ED8B00', logo: 'openjdk',           label: 'Java' },
  'Kotlin':         { color: '7F52FF', logo: 'kotlin',            label: 'Kotlin' },
  'Swift':          { color: 'F05138', logo: 'swift',             label: 'Swift' },
  'C#':             { color: '512BD4', logo: 'dotnet',            label: 'C#' },
  'C++':            { color: '00599C', logo: 'cplusplus',         label: 'C++' },
  'C':              { color: 'A8B9CC', logo: 'c',                 label: 'C' },
  'PHP':            { color: '777BB4', logo: 'php',               label: 'PHP' },
  'Ruby':           { color: 'CC342D', logo: 'ruby',              label: 'Ruby' },
  'Dart':           { color: '0175C2', logo: 'dart',              label: 'Dart' },
  'Scala':          { color: 'DC322F', logo: 'scala',             label: 'Scala' },
  'Elixir':         { color: '4B275F', logo: 'elixir',            label: 'Elixir' },
  'Haskell':        { color: '5D4F85', logo: 'haskell',           label: 'Haskell' },
  'Lua':            { color: '2C2D72', logo: 'lua',               label: 'Lua' },
  'Perl':           { color: '39457E', logo: 'perl',              label: 'Perl' },
  'R':              { color: '276DC3', logo: 'r',                 label: 'R' },
  'Julia':          { color: '9558B2', logo: 'julia',             label: 'Julia' },
  'MATLAB':         { color: '0076A8', logo: 'mathworks',         label: 'MATLAB' },
  'Zig':            { color: 'F7A41D', logo: 'zig',               label: 'Zig' },
  'V':              { color: '5D87BF', logo: 'v',                 label: 'V' },
  'Nim':            { color: 'FFE953', logo: 'nim',               label: 'Nim' },
  'Crystal':        { color: '000000', logo: 'crystal',           label: 'Crystal' },
  // Backend Frameworks
  'Node.js':        { color: '339933', logo: 'nodedotjs',         label: 'Node.js' },
  'Express':        { color: '000000', logo: 'express',           label: 'Express' },
  'Express.js':     { color: '000000', logo: 'express',           label: 'Express.js' },
  'NestJS':         { color: 'E0234E', logo: 'nestjs',            label: 'NestJS' },
  'FastAPI':        { color: '009688', logo: 'fastapi',           label: 'FastAPI' },
  'Django':         { color: '092E20', logo: 'django',            label: 'Django' },
  'Flask':          { color: '000000', logo: 'flask',             label: 'Flask' },
  'Laravel':        { color: 'FF2D20', logo: 'laravel',           label: 'Laravel' },
  'Spring':         { color: '6DB33F', logo: 'spring',            label: 'Spring' },
  'Spring Boot':    { color: '6DB33F', logo: 'springboot',        label: 'Spring Boot' },
  'Rails':          { color: 'CC0000', logo: 'rubyonrails',       label: 'Rails' },
  'Ruby on Rails':  { color: 'CC0000', logo: 'rubyonrails',       label: 'Ruby on Rails' },
  'Phoenix':        { color: 'FD4F00', logo: 'phoenixframework',  label: 'Phoenix' },
  'Gin':            { color: '00ADD8', logo: 'go',                label: 'Gin' },
  'Fiber':          { color: '00AED8', logo: 'go',                label: 'Fiber' },
  'Actix':          { color: '000000', logo: 'rust',              label: 'Actix' },
  'Axum':           { color: '000000', logo: 'rust',              label: 'Axum' },
  'Hono':           { color: 'E36002', logo: 'hono',              label: 'Hono' },
  'Fastify':        { color: '000000', logo: 'fastify',           label: 'Fastify' },
  'Koa':            { color: '33333D', logo: 'koa',               label: 'Koa' },
  'Strapi':         { color: '2F2E8B', logo: 'strapi',            label: 'Strapi' },
  'AdonisJS':       { color: '5A45FF', logo: 'adonisjs',          label: 'AdonisJS' },
  '.NET':           { color: '512BD4', logo: 'dotnet',            label: '.NET' },
  'ASP.NET':        { color: '512BD4', logo: 'dotnet',            label: 'ASP.NET' },
  // Databases
  'PostgreSQL':     { color: '4169E1', logo: 'postgresql',        label: 'PostgreSQL' },
  'Postgres':       { color: '4169E1', logo: 'postgresql',        label: 'PostgreSQL' },
  'MySQL':          { color: '4479A1', logo: 'mysql',             label: 'MySQL' },
  'MongoDB':        { color: '47A248', logo: 'mongodb',           label: 'MongoDB' },
  'SQLite':         { color: '003B57', logo: 'sqlite',            label: 'SQLite' },
  'Redis':          { color: 'DC382D', logo: 'redis',             label: 'Redis' },
  'Supabase':       { color: '3ECF8E', logo: 'supabase',          label: 'Supabase' },
  'Firebase':       { color: 'FFCA28', logo: 'firebase',          label: 'Firebase' },
  'PlanetScale':    { color: '000000', logo: 'planetscale',       label: 'PlanetScale' },
  'Neon':           { color: '00E699', logo: 'neon',              label: 'Neon' },
  'DynamoDB':       { color: '4053D6', logo: 'amazondynamodb',    label: 'DynamoDB' },
  'Cassandra':      { color: '1287B1', logo: 'apachecassandra',   label: 'Cassandra' },
  'Elasticsearch':  { color: '005571', logo: 'elasticsearch',     label: 'Elasticsearch' },
  'CockroachDB':    { color: '6933FF', logo: 'cockroachlabs',     label: 'CockroachDB' },
  'Neo4j':          { color: '008CC1', logo: 'neo4j',             label: 'Neo4j' },
  'MariaDB':        { color: '003545', logo: 'mariadb',           label: 'MariaDB' },
  'Oracle':         { color: 'F80000', logo: 'oracle',            label: 'Oracle' },
  'Microsoft SQL Server': { color: 'CC2927', logo: 'microsoftsqlserver', label: 'SQL Server' },
  'InfluxDB':       { color: '22ADF6', logo: 'influxdb',          label: 'InfluxDB' },
  'Prisma':         { color: '2D3748', logo: 'prisma',            label: 'Prisma' },
  'Drizzle':        { color: 'C5F74F', logo: 'drizzle',           label: 'Drizzle' },
  'Mongoose':       { color: '880000', logo: 'mongoose',          label: 'Mongoose' },
  // Cloud & DevOps
  'AWS':            { color: 'FF9900', logo: 'amazonaws',         label: 'AWS' },
  'Google Cloud':   { color: '4285F4', logo: 'googlecloud',       label: 'Google Cloud' },
  'GCP':            { color: '4285F4', logo: 'googlecloud',       label: 'GCP' },
  'Azure':          { color: '0078D4', logo: 'microsoftazure',    label: 'Azure' },
  'Vercel':         { color: '000000', logo: 'vercel',            label: 'Vercel' },
  'Netlify':        { color: '00C7B7', logo: 'netlify',           label: 'Netlify' },
  'Heroku':         { color: '430098', logo: 'heroku',            label: 'Heroku' },
  'DigitalOcean':   { color: '0080FF', logo: 'digitalocean',      label: 'DigitalOcean' },
  'Cloudflare':     { color: 'F38020', logo: 'cloudflare',        label: 'Cloudflare' },
  'Docker':         { color: '2496ED', logo: 'docker',            label: 'Docker' },
  'Kubernetes':     { color: '326CE5', logo: 'kubernetes',        label: 'Kubernetes' },
  'Terraform':      { color: '844FBA', logo: 'terraform',         label: 'Terraform' },
  'Ansible':        { color: 'EE0000', logo: 'ansible',           label: 'Ansible' },
  'GitHub Actions': { color: '2088FF', logo: 'githubactions',     label: 'GitHub Actions' },
  'Jenkins':        { color: 'D24939', logo: 'jenkins',           label: 'Jenkins' },
  'CircleCI':       { color: '343434', logo: 'circleci',          label: 'CircleCI' },
  'GitLab CI':      { color: 'FC6D26', logo: 'gitlab',            label: 'GitLab CI' },
  'Travis CI':      { color: '3EAAAF', logo: 'travisci',          label: 'Travis CI' },
  // Mobile
  'React Native':   { color: '61DAFB', logo: 'react',             label: 'React Native' },
  'Flutter':        { color: '02569B', logo: 'flutter',           label: 'Flutter' },
  'Expo':           { color: '000020', logo: 'expo',              label: 'Expo' },
  'Ionic':          { color: '3880FF', logo: 'ionic',             label: 'Ionic' },
  'Capacitor':      { color: '119EFF', logo: 'capacitor',         label: 'Capacitor' },
  'Android':        { color: '34A853', logo: 'android',           label: 'Android' },
  'iOS':            { color: '000000', logo: 'apple',             label: 'iOS' },
  // Testing
  'Jest':           { color: 'C21325', logo: 'jest',              label: 'Jest' },
  'Vitest':         { color: '6E9F18', logo: 'vitest',            label: 'Vitest' },
  'Cypress':        { color: '69D3A7', logo: 'cypress',           label: 'Cypress' },
  'Playwright':     { color: '2EAD33', logo: 'playwright',        label: 'Playwright' },
  'Testing Library':{ color: 'E33332', logo: 'testinglibrary',    label: 'Testing Library' },
  'Mocha':          { color: '8D6748', logo: 'mocha',             label: 'Mocha' },
  'pytest':         { color: '0A9EDC', logo: 'pytest',            label: 'pytest' },
  'Storybook':      { color: 'FF4785', logo: 'storybook',         label: 'Storybook' },
  // Build Tools
  'Vite':           { color: '646CFF', logo: 'vite',              label: 'Vite' },
  'Webpack':        { color: '8DD6F9', logo: 'webpack',           label: 'Webpack' },
  'Rollup':         { color: 'EC4A3F', logo: 'rollupdotjs',       label: 'Rollup' },
  'esbuild':        { color: 'FFCF00', logo: 'esbuild',           label: 'esbuild' },
  'Parcel':         { color: 'B93C10', logo: 'parcel',            label: 'Parcel' },
  'Turbopack':      { color: 'EF4444', logo: 'turbo',             label: 'Turbopack' },
  'Bun':            { color: 'FBF0DF', logo: 'bun',               label: 'Bun' },
  'Deno':           { color: '000000', logo: 'deno',              label: 'Deno' },
  'pnpm':           { color: 'F69220', logo: 'pnpm',              label: 'pnpm' },
  'npm':            { color: 'CB3837', logo: 'npm',               label: 'npm' },
  'Yarn':           { color: '2C8EBB', logo: 'yarn',              label: 'Yarn' },
  // State Management
  'Redux':          { color: '764ABC', logo: 'redux',             label: 'Redux' },
  'Zustand':        { color: '433E38', logo: 'zustand',           label: 'Zustand' },
  'MobX':           { color: 'FF7102', logo: 'mobx',              label: 'MobX' },
  'Jotai':          { color: 'FFFFFF', logo: 'jotai',             label: 'Jotai' },
  'Recoil':         { color: '1F69FF', logo: 'recoil',            label: 'Recoil' },
  'Pinia':          { color: 'FFD859', logo: 'pinia',             label: 'Pinia' },
  'XState':         { color: '2C3E50', logo: 'xstate',            label: 'XState' },
  // APIs
  'GraphQL':        { color: 'E10098', logo: 'graphql',           label: 'GraphQL' },
  'Apollo':         { color: '311C87', logo: 'apollographql',     label: 'Apollo' },
  'tRPC':           { color: '398CCB', logo: 'trpc',              label: 'tRPC' },
  'REST API':       { color: '009688', logo: 'fastapi',           label: 'REST API' },
  'gRPC':           { color: '244C5A', logo: 'grpc',              label: 'gRPC' },
  // Auth
  'Auth.js':        { color: 'BB2929', logo: 'auth0',             label: 'Auth.js' },
  'NextAuth':       { color: 'BB2929', logo: 'auth0',             label: 'NextAuth' },
  'Clerk':          { color: '6C47FF', logo: 'clerk',             label: 'Clerk' },
  'Auth0':          { color: 'EB5424', logo: 'auth0',             label: 'Auth0' },
  'Passport.js':    { color: '34E27A', logo: 'passport',          label: 'Passport.js' },
  // Tools
  'Git':            { color: 'F05032', logo: 'git',               label: 'Git' },
  'GitHub':         { color: '181717', logo: 'github',            label: 'GitHub' },
  'GitLab':         { color: 'FC6D26', logo: 'gitlab',            label: 'GitLab' },
  'Bitbucket':      { color: '0052CC', logo: 'bitbucket',         label: 'Bitbucket' },
  'Linux':          { color: 'FCC624', logo: 'linux',             label: 'Linux' },
  'Ubuntu':         { color: 'E95420', logo: 'ubuntu',            label: 'Ubuntu' },
  'macOS':          { color: '000000', logo: 'apple',             label: 'macOS' },
  'Windows':        { color: '0078D4', logo: 'windows',           label: 'Windows' },
  'VS Code':        { color: '007ACC', logo: 'visualstudiocode',  label: 'VS Code' },
  'Figma':          { color: 'F24E1E', logo: 'figma',             label: 'Figma' },
  'Postman':        { color: 'FF6C37', logo: 'postman',           label: 'Postman' },
  'Jira':           { color: '0052CC', logo: 'jira',              label: 'Jira' },
  'Notion':         { color: '000000', logo: 'notion',            label: 'Notion' },
  'Slack':          { color: '4A154B', logo: 'slack',             label: 'Slack' },
  'Nginx':          { color: '009639', logo: 'nginx',             label: 'Nginx' },
  // AI / ML
  'TensorFlow':     { color: 'FF6F00', logo: 'tensorflow',        label: 'TensorFlow' },
  'PyTorch':        { color: 'EE4C2C', logo: 'pytorch',           label: 'PyTorch' },
  'Hugging Face':   { color: 'FFD21E', logo: 'huggingface',       label: 'Hugging Face' },
  'OpenAI':         { color: '412991', logo: 'openai',            label: 'OpenAI' },
  'LangChain':      { color: '1C3C3C', logo: 'langchain',         label: 'LangChain' },
  'scikit-learn':   { color: 'F7931E', logo: 'scikitlearn',       label: 'scikit-learn' },
  'pandas':         { color: '150458', logo: 'pandas',            label: 'pandas' },
  'NumPy':          { color: '013243', logo: 'numpy',             label: 'NumPy' },
  'Jupyter':        { color: 'F37626', logo: 'jupyter',           label: 'Jupyter' },
  // Misc
  'Stripe':         { color: '635BFF', logo: 'stripe',            label: 'Stripe' },
  'Twilio':         { color: 'F22F46', logo: 'twilio',            label: 'Twilio' },
  'Sendgrid':       { color: '1A82E2', logo: 'sendgrid',          label: 'SendGrid' },
  'Pusher':         { color: '300D4F', logo: 'pusher',            label: 'Pusher' },
  'Socket.io':      { color: '010101', logo: 'socketdotio',       label: 'Socket.io' },
  'WebSocket':      { color: '010101', logo: 'socketdotio',       label: 'WebSocket' },
  'Electron':       { color: '47848F', logo: 'electron',          label: 'Electron' },
  'Tauri':          { color: '24C8D8', logo: 'tauri',             label: 'Tauri' },
  'Unity':          { color: '000000', logo: 'unity',             label: 'Unity' },
  'Unreal Engine':  { color: '0E1128', logo: 'unrealengine',      label: 'Unreal Engine' },
  'WordPress':      { color: '21759B', logo: 'wordpress',         label: 'WordPress' },
  'Shopify':        { color: '96BF48', logo: 'shopify',           label: 'Shopify' },
  'Sanity':         { color: 'F03E2F', logo: 'sanity',            label: 'Sanity' },
  'Contentful':     { color: '2478CC', logo: 'contentful',        label: 'Contentful' },
  'Poetry':         { color: '60A5FA', logo: 'poetry',            label: 'Poetry' },
  'pip':            { color: '3775A9', logo: 'pypi',              label: 'pip' },
  'Cargo':          { color: 'F74C00', logo: 'rust',              label: 'Cargo' },
  'Maven':          { color: 'C71A36', logo: 'apachemaven',       label: 'Maven' },
  'Gradle':         { color: '02303A', logo: 'gradle',            label: 'Gradle' },
  'RabbitMQ':       { color: 'FF6600', logo: 'rabbitmq',          label: 'RabbitMQ' },
  'Kafka':          { color: '231F20', logo: 'apachekafka',       label: 'Kafka' },
  'Celery':         { color: '37814A', logo: 'celery',            label: 'Celery' },
  'Nginx':          { color: '009639', logo: 'nginx',             label: 'Nginx' },
  'Apache':         { color: 'D22128', logo: 'apache',            label: 'Apache' },
  'Traefik':        { color: '24A1C1', logo: 'traefikproxy',      label: 'Traefik' },
  'Prometheus':     { color: 'E6522C', logo: 'prometheus',        label: 'Prometheus' },
  'Grafana':        { color: 'F46800', logo: 'grafana',           label: 'Grafana' },
  'Sentry':         { color: '362D59', logo: 'sentry',            label: 'Sentry' },
  'Datadog':        { color: '632CA6', logo: 'datadog',           label: 'Datadog' },
};

export const ALL_TECH_NAMES = Object.keys(TECH_LOGOS);

/** Returns a shields.io badge img URL for a tech item, with its logo */
export function getTechBadgeUrl(techName) {
  const info = TECH_LOGOS[techName];
  if (info) {
    const labelEncoded = encodeURIComponent(info.label).replace(/-/g, '--').replace(/_/g, '__');
    return `https://img.shields.io/badge/${labelEncoded}-${info.color}?style=flat-square&logo=${info.logo}&logoColor=white`;
  }
  // Fallback: generate a plain grey badge
  const labelEncoded = encodeURIComponent(techName).replace(/-/g, '--').replace(/_/g, '__');
  return `https://img.shields.io/badge/${labelEncoded}-555555?style=flat-square`;
}

/** Returns the markdown img tag for a badge */
export function getTechBadgeMd(techName) {
  return `![${techName}](${getTechBadgeUrl(techName)})`;
}
